/**
 * Generates docs/CHART-CONTRACTS.md from the chart registry so the document
 * cannot drift from the code. `--check` fails if the file is out of date.
 */
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const registry = JSON.parse(await readFile(path.join(root, 'modules/extended-charts/registry/charts.json'), 'utf8'));
const target = path.join(root, 'docs/CHART-CONTRACTS.md');

const RULE_TEXT = {
	numeric_only: 'Mapped items must be numeric (float or unsigned).',
	has_values: 'At least one item has a recent value; items without one are shown as no data, never zero.',
	same_units: 'All series share units; otherwise the widget reports the incompatible units.',
	non_negative: 'Values must not be negative.',
	non_negative_size: 'Bubble sizes must not be negative.',
	has_target: 'Every actual value has a target from an item, a macro or a constant. Targets are never derived from the actual value.',
	min_dimensions: 'At least `min_dimensions` distinct items act as axes.',
	radar_scale: 'Shared scale requires common units and a positive maximum; per-axis scale uses each axis\'s largest real value.',
	colour_bounds: 'Configured colour bounds are numbers with minimum below maximum; time buckets are valid.',
	has_history: 'Every mapped item has history in the period; at most `max_items` items per role.',
	ohlc_consistent: 'Explicit OHLC candles satisfy low <= open, close <= high; periods missing a component are skipped and reported.',
	complete_tuples: 'Every pairing key (host or tag value) has exactly one item for each required role.',
	valid_intervals: 'Each task has a positive start and an end at or after it (or a non-negative duration).',
	hierarchy_source: 'The hierarchy comes from host groups, named tags, or item names split by an explicit delimiter.',
	has_edges: 'Relationships come from an explicit list or a host tag naming the peer host. None are inferred.',
	edges_resolve: 'Every relationship endpoint is one of the selected hosts.',
	relationship_tags: 'Every item carries both the source and the target tag.'
};

const lines = [
	'# Chart contracts',
	'',
	'<!-- Generated by scripts/contracts-doc.mjs from modules/extended-charts/registry/charts.json. Do not edit by hand. -->',
	'',
	'A chart renders only when its contract is met. Otherwise the widget shows the reasons. No chart invents targets, OHLC values, timestamps, durations, topology, hierarchy or flow weights.',
	'',
	'Conditions such as `when:ohlc_mode=explicit` mean the requirement applies only for that setting.',
	''
];

for (const chart of registry.charts) {
	lines.push(`## ${chart.code} ${chart.name} (\`${chart.id}\`)`, '');
	lines.push('| Role | Form field | Required | Numeric | Max items |', '|---|---|---|---|---|');
	for (const [name, role] of Object.entries(chart.roles)) {
		lines.push(`| ${name} | \`${role.field}\` | ${role.required === true ? 'yes' : role.required === false ? 'no' : `\`${role.required}\``} | ${role.numeric ? 'yes' : 'no'} | ${role.max_items ?? ''} |`);
	}
	lines.push('');
	lines.push(`- **Data fetched:** ${chart.data.join(', ')}`);
	lines.push(`- **History:** \`${chart.history}\`; **time period:** \`${chart.time_period}\``);
	if (chart.min_dimensions) {
		lines.push(`- **Minimum dimensions:** ${chart.min_dimensions}`);
	}
	if (chart.aggregations.length > 0) {
		lines.push(`- **Aggregations:** ${chart.aggregations.join(', ')}`);
	}
	lines.push(`- **Controls:** ${chart.controls.map((control) => `\`${control}\``).join(', ')}`);
	lines.push('- **Rules:**');
	for (const rule of chart.rules) {
		lines.push(`  - \`${rule}\`: ${RULE_TEXT[rule] ?? 'undocumented rule'}`);
	}
	lines.push('');
}

const text = `${lines.join('\n').trimEnd()}\n`;

if (process.argv.includes('--check')) {
	const current = await readFile(target, 'utf8').catch(() => '');
	if (current !== text) {
		console.error('docs/CHART-CONTRACTS.md is out of date. Run: npm run docs:contracts');
		process.exit(1);
	}
	console.log('docs/CHART-CONTRACTS.md is up to date.');
}
else {
	await writeFile(target, text);
	console.log('Wrote docs/CHART-CONTRACTS.md');
}
