/**
 * Regenerates src/data/geo/world-land.js, the world outline the Geographic
 * Site Map draws by default, from Natural Earth's 1:110m land polygons
 * (public domain, naturalearthdata.com).
 *
 * Usage: node scripts/world-land.mjs path/to/ne_110m_land.geojson
 *
 * Coordinates are rounded to two decimal places (about a kilometre), which
 * is far finer than the 1:110m source and keeps the bundle small.
 */
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const source = process.argv[2];
if (!source) {
	throw new Error('Give the path of ne_110m_land.geojson.');
}

const input = JSON.parse(await readFile(source, 'utf8'));
const round = (value) => Math.round(value * 100) / 100;
const ring = (points) => points.map(([lon, lat]) => [round(lon), round(lat)])
	.filter((point, index, list) => index === 0 || point[0] !== list[index - 1][0] || point[1] !== list[index - 1][1]);

const features = input.features.map((feature, index) => ({
	type: 'Feature',
	properties: { name: `land-${index + 1}` },
	geometry: feature.geometry.type === 'Polygon'
		? { type: 'Polygon', coordinates: feature.geometry.coordinates.map(ring) }
		: { type: 'MultiPolygon', coordinates: feature.geometry.coordinates.map((polygon) => polygon.map(ring)) }
}));

const body = JSON.stringify({ type: 'FeatureCollection', features });
await writeFile(path.join(root, 'src/data/geo/world-land.js'), `/**
 * World land outline for the Geographic Site Map: Natural Earth 1:110m land
 * polygons (public domain, naturalearthdata.com), coordinates
 * rounded to two decimal places. Generated by scripts/world-land.mjs; do not
 * edit by hand. It is bundled with the module, so no map is fetched.
 */
export default ${body};
`);
console.log(`Wrote ${features.length} land polygons (${body.length} bytes).`);
